set(FFMPEG_FOUND FALSE)
set(FFMPEG_LIBAVCODEC_FOUND FALSE)
set(FFMPEG_libavcodec_FOUND FALSE)
set(FFMPEG_LIBAVFORMAT_FOUND FALSE)
set(FFMPEG_libavformat_FOUND FALSE)
set(FFMPEG_LIBAVUTIL_FOUND FALSE)
set(FFMPEG_libavutil_FOUND FALSE)
set(FFMPEG_LIBSWSCALE_FOUND FALSE)
set(FFMPEG_libswscale_FOUND FALSE)
set(FFMPEG_LIBAVRESAMPLE_FOUND FALSE)
set(FFMPEG_libavresample_FOUND FALSE)

find_path(FFMPEG_INCLUDE_DIR NAMES "libavcodec/version.h" PATHS ${CONAN_INCLUDE_DIRS_FFMPEG})

find_library(FFMPEG_LIBAVCODEC_LIBRARY NAMES avcodec PATHS ${CONAN_LIB_DIRS_FFMPEG} NO_DEFAULT_PATH)
find_library(FFMPEG_LIBAVFORMAT_LIBRARY NAMES avformat PATHS ${CONAN_LIB_DIRS_FFMPEG} NO_DEFAULT_PATH)
find_library(FFMPEG_LIBAVUTIL_LIBRARY NAMES avutil PATHS ${CONAN_LIB_DIRS_FFMPEG} NO_DEFAULT_PATH)
find_library(FFMPEG_LIBSWSCALE_LIBRARY NAMES swscale PATHS ${CONAN_LIB_DIRS_FFMPEG} NO_DEFAULT_PATH)
find_library(FFMPEG_LIBAVRESAMPLE_LIBRARY NAMES avresample PATHS ${CONAN_LIB_DIRS_FFMPEG} NO_DEFAULT_PATH)

if(FFMPEG_INCLUDE_DIR AND FFMPEG_LIBAVCODEC_LIBRARY AND FFMPEG_LIBAVFORMAT_LIBRARY AND FFMPEG_LIBAVUTIL_LIBRARY AND FFMPEG_LIBSWSCALE_LIBRARY)
    set(FFMPEG_FOUND TRUE)

    set(FFMPEG_LIBAVUTIL_FOUND TRUE)
    set(FFMPEG_LIBSWSCALE_FOUND TRUE)
    set(FFMPEG_LIBAVCODEC_FOUND TRUE)
    set(FFMPEG_LIBAVFORMAT_FOUND TRUE)
    
    set(FFMPEG_libavutil_FOUND TRUE)
    set(FFMPEG_libswscale_FOUND TRUE)
    set(FFMPEG_libavcodec_FOUND TRUE)
    set(FFMPEG_libavformat_FOUND TRUE)
    
    set(FFMPEG_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
    set(FFMPEG_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
    set(FFMPEG_LIBRARIES ${FFMPEG_LIBAVUTIL_LIBRARY} ${FFMPEG_LIBSWSCALE_LIBRARY} ${FFMPEG_LIBAVCODEC_LIBRARY} ${FFMPEG_LIBAVFORMAT_LIBRARY})

    # This is a per libraries definition for openCV
    set(FFMPEG_LIBAVUTIL_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
    set(FFMPEG_LIBSWSCALE_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
    set(FFMPEG_LIBAVCODEC_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
    set(FFMPEG_LIBAVFORMAT_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})

    set(FFMPEG_LIBAVUTIL_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
    set(FFMPEG_LIBSWSCALE_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
    set(FFMPEG_LIBAVCODEC_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
    set(FFMPEG_LIBAVFORMAT_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})

    set(FFMPEG_LIBAVUTIL_LIBRARIES ${FFMPEG_LIBAVUTIL_LIBRARY})
    set(FFMPEG_LIBSWSCALE_LIBRARIES ${FFMPEG_LIBSWSCALE_LIBRARY})
    set(FFMPEG_LIBAVCODEC_LIBRARIES ${FFMPEG_LIBAVCODEC_LIBRARY})
    set(FFMPEG_LIBAVFORMAT_LIBRARIES ${FFMPEG_LIBAVFORMAT_LIBRARY})

    set(FFMPEG_libavutil_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
    set(FFMPEG_libswscale_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
    set(FFMPEG_libavcodec_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
    set(FFMPEG_LIBAVFORMAT_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})

    set(FFMPEG_libavutil_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
    set(FFMPEG_libswscale_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
    set(FFMPEG_libavcodec_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
    set(FFMPEG_libavformat_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})

    set(FFMPEG_libavutil_LIBRARIES ${FFMPEG_LIBAVUTIL_LIBRARY})
    set(FFMPEG_libswscale_LIBRARIES ${FFMPEG_LIBSWSCALE_LIBRARY})
    set(FFMPEG_libavcodec_LIBRARIES ${FFMPEG_LIBAVCODEC_LIBRARY})
    set(FFMPEG_libavformat_LIBRARIES ${FFMPEG_LIBAVFORMAT_LIBRARY})

    # Optionnal libavresample
    if(FFMPEG_LIBAVRESAMPLE_LIBRARY)
        set(FFMPEG_LIBAVRESAMPLE_FOUND TRUE)
        set(FFMPEG_libavresample_FOUND TRUE)
        list(APPEND FFMPEG_LIBRARIES ${FFMPEG_LIBAVRESAMPLE_LIBRARY})

        set(FFMPEG_LIBAVRESAMPLE_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
        set(FFMPEG_LIBAVRESAMPLE_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
        set(FFMPEG_LIBAVRESAMPLE_LIBRARIES ${FFMPEG_LIBAVRESAMPLE_LIBRARY})

        set(FFMPEG_libavresample_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})
        set(FFMPEG_libavresample_LIBRARY_DIRS ${CONAN_LIB_DIRS_FFMPEG})
        set(FFMPEG_libavresample_LIBRARIES ${FFMPEG_LIBAVRESAMPLE_LIBRARY})

        mark_as_advanced(
            FFMPEG_LIBAVRESAMPLE_INCLUDE_DIRS
            FFMPEG_LIBAVRESAMPLE_LIBRARIES
            FFMPEG_libavresample_INCLUDE_DIRS
            FFMPEG_libavresample_LIBRARIES
        )
    endif()

    mark_as_advanced(
        FFMPEG_INCLUDE_DIR
        FFMPEG_LIBRARIES
        FFMPEG_LIBAVUTIL_INCLUDE_DIRS
        FFMPEG_LIBAVUTIL_LIBRARIES
        FFMPEG_LIBSWSCALE_INCLUDE_DIRS
        FFMPEG_LIBSWSCALE_LIBRARIES
        FFMPEG_LIBAVCODEC_INCLUDE_DIRS
        FFMPEG_LIBAVCODEC_LIBRARIES
        FFMPEG_LIBAVFORMAT_INCLUDE_DIRS
        FFMPEG_LIBAVFORMAT_LIBRARIES
        FFMPEG_libavutil_INCLUDE_DIRS
        FFMPEG_libavutil_LIBRARIES
        FFMPEG_libswscale_INCLUDE_DIRS
        FFMPEG_libswscale_LIBRARIES
        FFMPEG_libavcodec_INCLUDE_DIRS
        FFMPEG_libavcodec_LIBRARIES
        FFMPEG_libavformat_INCLUDE_DIRS
        FFMPEG_libavformat_LIBRARIES
    )
endif()

message(STATUS "(FFMPEG_FOUND : ${FFMPEG_FOUND} include: ${FFMPEG_INCLUDE_DIRS}, lib: ${FFMPEG_LIBRARIES})")
